name: email_sending

on:
  schedule:
    - cron: "0 19 * * 0"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - name: Send email
        env:
          I_EMAIL: ${{ secrets.I_EMAIL }}
          V_EMAIL: ${{ secrets.V_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PWORD: ${{ secrets.SENDER_PWORD }}
        run: python3 script.py
      - name: Push to github
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
